#bootstrap and build
before_script: 'echo "branch: $TRAVIS_BRANCH" >> _config_test.yml'

script: "./script/cibuild"

#environment
language: ruby

rvm:
  - 2.1.4

cache: bundler
sudo: false

env:
  global:
    NOKOGIRI_USE_SYSTEM_LIBRARIES=true
