title: Ben Balter
description: Attorney, open source developer, product manager
author:
  name: Ben Balter
  twitter: benbalter
url: https://ben.balter.com

repository: benbalter/benbalter.github.com
logo: "/assets/img/headshot.jpg"

twitter:
  username: "@benbalter"

social:
  name: Ben Balter
  links:
    - https://twitter.com/BenBalter
    - https://www.facebook.com/ben.balter
    - https://www.linkedin.com/in/BenBalter
    - https://plus.google.com/+BenBalter
    - https://github.com/benbalter
    - https://keybase.io/benbalter

disqus:
  shortname: benbalter

google_plus_id: BenBalter
ga_username: UA-18088627-1

exclude:
  - CONTRIBUTING.md
  - README.md
  - LICENSE
  - readme.md
  - bundle
  - src
  - CNAME
  - Gemfile
  - Gemfile.lock
  - bower.json
  - package.json
  - script
  - test
  - less
  - scss
  - media
  - feature-detects
  - composer.json
  - component.json
  - grunt.js
  - assets/vendor/bootstrap-sass/stylesheets
  - assets/vendor/font-awesome/less
  - assets/vendor/font-awesome/scss
  - assets/vendor/font-awesome/src
  - assets/vendor/modernizr/feature-detects
  - assets/vendor/modernizr/media
  - assets/vendor/modernizr/test
  - assets/vendor/anchor-js/README.md
  - ".bundle"
  - vendor
  - node_modules
  - Rakefile
  - retlab

permalink: "/:year/:month/:day/:title/"
defaults:
  - scope:
      path: ''
      type: posts
    values:
      layout: post
      comments: true
  - scope:
      path: ''
      type: pages
    values:
      layout: page
      comments: false

timezone: America/New_York
encoding: UTF-8
lang: en-US
branch: master
future: true

plugins:
  - jemoji
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-avatar
  - jekyll-github-metadata
#  - jekyll-admin

sass:
  style: :compressed
  sass_dir: retlab/_sass
includes_dir: retlab/_includes
layouts_dir: retlab/_layouts

gist:
  noscript: false

collections:
  - resume_positions

nav_pages:
  - index.html
  - talks.md
  - press.md
  - about.md
  - contact.md

contact_links:
  - name: Twitter
    url: https://twitter.com/BenBalter
    icon: twitter
  - name: Facebook
    url: https://facebook.com/BenBalter
    icon: facebook
  - name: LinkedIn
    url: https://www.linkedin.com/in/BenBalter
    icon: linkedin
  - name: Google
    url: https://plus.google.com/107848665104278257250?rel=author
    icon: google-plus
  - name: GitHub
    url: https://github.com/benbalter
    icon: github
  - name: Keybase
    url: https://keybase.io/benbalter
    icon: key

amazon:
  affiliates_tag: benbalter07-20
