#Jekyll config file

#title of site
name: Ben Balter

#description of site
description: "GitHubber, Gov 2.0 Evangelist, Aspiring Attorney"

#URL of site, include http://, do not include a trailing slash
url: http://ben.balter.com

#files to exclude, array
exclude: [ 'readme.md', 'php', 'node_modules', 'Gruntfile.coffee', 'package.json' ]

#posts per page
paginate: 10

#number of items in RSS feed
rss_limit: 10

#permalink structure, see https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:year/:month/:day/:title/

#prose config, see http://prose.io/help/handbook.html
#prose:
  metadata:
    "_posts": |
      title: "Title of the post"
      excerpt: "SEO friendly description"
      author: "Your Name Here"
      layout: post
      comments: true
      category: 
      tags: 
      published: false
    "": |
      title: "Title of the page"
      excerpt: "SEO friendly description"
      layout: page
      published: false
    
#Twitter Widget
twitter: 
  username: "benbalter"
  count: 5
  
#disqus widget
disqus:
  shortname: 'benbalter'
  count: 5
  api_key: "OQ5OlN2AtWDfIQ0bjIGwdfq9SsEB3P8NdzhYTRak7R45KeAD744aVIqJZDYqvmuL"
  
#google analytics username
ga_username: 'UA-18088627-1'

#build config
server: true
auto: true
pygments: true
