#Jekyll config file

name: Ben Balter
description: "Government evangelist, attorney, open source developer"
gravatar_id: ea353bd28baa1aefaefae736a19fcf2a
job_title: Government Evangelist
employer: GitHub
url: "http://ben.balter.com"
location:
  city: Washington
  state: District of Columbia
  country: United States of America
ga_username: 'UA-18088627-1'
twitter:
  username: "@benbalter"
  account_id: "16211142"
google_plus_id: BenBalter

#files to exclude, array
exclude:
  - CONTRIBUTING.md
  - README.md
  - LICENSE
  - readme.md
  - bundle
  - src
  - CNAME
  - Gemfile
  - Gemfile.lock
  - bower.json
  - package.json
  - script
  - test
  - less
  - scss
  - media
  - feature-detects
  - composer.json
  - component.json
  - grunt.js
  - assets/vendor/font-awesome/src
  - assets/vendor/bootstrap/js
  - assets/vendor/bootstrap/less
  - assets/vendor/font-awesome/less
  - assets/vendor/font-awesome/scss
  - assets/vendor/font-awesome/src
  - assets/vendor/modernizr/feature-detects
  - assets/vendor/modernizr/media
  - assets/vendor/modernizr/test
  - ".bundle"
  - vendor

#number of items in RSS feed
rss_limit: 10

#permalink structure, see https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:year/:month/:day/:title/

# Frontmatter defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true

#disqus widget
disqus:
  shortname: 'benbalter'
  count: 5
  api_key: "OQ5OlN2AtWDfIQ0bjIGwdfq9SsEB3P8NdzhYTRak7R45KeAD744aVIqJZDYqvmuL"

#build config
highlighter: pygments
markdown: kramdown
timezone: America/New_York
encoding: UTF-8

gems:
  - jemoji
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-sitemap
