#Jekyll config file

# Basics
name: Ben Balter
title: Ben Balter
description: "Attorney, open source developer, product manager"
author: benbalter
repository: benbalter/benbalter.github.com

# Images
gravatar_id: ea353bd28baa1aefaefae736a19fcf2a

# RDFa structured data
job_title: Product Manager
employer: GitHub
url: "http://ben.balter.com"
location:
  city: Washington
  state: District of Columbia
  country: United States of America

# Social metadata (JSON-LD)
social:
  name: Ben Balter
  links:
    - https://twitter.com/BenBalter
    - https://www.facebook.com/ben.balter
    - https://www.linkedin.com/in/BenBalter
    - https://plus.google.com/+BenBalter
    - https://github.com/benbalter
    - https://keybase.io/benbalter

logo: /assets/img/headshot.jpg

# Misc
twitter:
  username: "@benbalter"
google_plus_id: BenBalter
ga_username: 'UA-18088627-1'

#files to exclude, array
exclude:
  - CONTRIBUTING.md
  - README.md
  - LICENSE
  - readme.md
  - bundle
  - src
  - CNAME
  - Gemfile
  - Gemfile.lock
  - bower.json
  - package.json
  - script
  - test
  - less
  - scss
  - media
  - feature-detects
  - composer.json
  - component.json
  - grunt.js
  - assets/vendor/bootstrap-sass/stylesheets
  - assets/vendor/font-awesome/less
  - assets/vendor/font-awesome/scss
  - assets/vendor/font-awesome/src
  - assets/vendor/modernizr/feature-detects
  - assets/vendor/modernizr/media
  - assets/vendor/modernizr/test
  - assets/vendor/anchor-js/index.html
  - ".bundle"
  - vendor
  - node_modules
  - Rakefile

#number of items in RSS feed
rss_limit: 10

#permalink structure, see http://jekyllrb.com/docs/permalinks/
permalink: /:year/:month/:day/:title/

# Frontmatter defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      comments: true
      author: benbalter

#disqus widget
disqus:
  shortname: 'benbalter'
  count: 5
  api_key: "OQ5OlN2AtWDfIQ0bjIGwdfq9SsEB3P8NdzhYTRak7R45KeAD744aVIqJZDYqvmuL"

#build config
timezone: America/New_York
encoding: UTF-8
branch: master

gems:
  - jemoji
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-avatar
  - jekyll-github-metadata

sass:
  style: :compressed

kramdown:
 input: GFM
 hard_wrap: false

highlighter: rouge
gist:
 noscript: false
future: true

lang: en-US

collections:
  - resume_positions
